name: DotNet Build

on:
  push:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show .NET Version
        run: dotnet --version

      - name: Restore Packages
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Release
